name: rakudasu_mobile
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  firebase_core: ^0.5.3
  cloud_firestore: ^0.14.4
  firebase_auth: ^0.18.4+1

  provider: ^4.1.3
  firebase_storage: ^4.0.0
  flutter_hooks: ^0.14.0
  hooks_riverpod: ^0.11.1
  state_notifier: ^0.6.0
  freezed_annotation: ^0.12.0

  intl: ^0.16.1
  table_calendar: ^2.3.3
  flutter_datetime_picker: ^1.4.0
  flutter_cupertino_datetime_picker: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/

fonts:
  - family: HachiMaruPop-Regular
    fonts:
      - asset: fonts/HachiMaruPop-Regular.ttf
